### PR TITLE
Added unit test to read incomplete mp3 file; added incomplete mp3 file.

### PR DESCRIPTION
**Pull request by codealchemist**

### CODE REVIEW

**Comment by Borewit** [comment]
Thanks again for your thorough feedback. I don’t have my development tools around for a few days, I will look into it when I arrive home.

Just a few things I notice. If your intend is to simulate a partial downloaded file, it is read as stream not as a file. I assume the stream stops a the first “gap”. I don’t think the ID3v1 header can be read this way, because these are the last 128 bytes of the stream/file.

**Comment by Borewit** [comment]
To give this test a better home then ID3v1, I created a [generic MP3 parsing file: test-mp3.ts](https://github.com/Borewit/music-metadata/blob/master/test/test-mp3.ts). Can you please move the test in there?

Alberto I think we should either use the file parser for partial downloaded file (as you have done in your test now), or do additional tests with streams based on partial downloaded file, in such a way that it reflects the [webtorrent-desktop](https://webtorrent.io/desktop/) context.

**Comment by codealchemist** [comment]
Sure, I'll move the test there.
Thx!

I think both cases, a partially downloaded file, and an unfinished stream, are valid use cases.
Might be good to test both.
What do you think?

**Comment by Borewit** [comment]
> I think both cases, a partially downloaded file, and an unfinished stream, are valid use cases.
> Might be good to test both.
> What do you think?

In principle I agree it could be valid use cases, adding a disclaimer to the partial downloaded files, hard to predict the exact behavior. The file is broken after all.

I don't know what the best strategy is for [webtorrent-desktop](https://webtorrent.io/desktop/), I suggest we address this as an separate issue, together with an improved update mechanism for the metadata, which is in my opinion related to this.

Therefor I opened a new issue to capture this: webtorrent/webtorrent-desktop#1340

**Comment by codealchemist** [comment]
Sounds good!
Thanks!

**Pull request merged**
