### PR TITLE
Add check for unknown dataFormat

### PR DESCRIPTION
**Pull request by bhj**
Thanks for all your work on this great library! This fixes "Cannot read property 'lossy' of undefined" on v5.x, with my very simple MP4s at least:

Screen Shot 2019-12-03 at 12 01 52 PM

### CODE REVIEW

**Comment by bhj** [comment]
Ah, good call, done!

**Comment by Borewit** [comment]
Glad you like the library, forgot to say that.

Oh, mm, yeah, maybe the issue is a bit more nasty as it initially liked. I think the [`avc1`](https://en.wikipedia.org/wiki/Advanced_Video_Coding) is a video codec, and the lossy flag should be based on the audio codec.

So the `avc1` does not belong there. I will strip of your last commit and
1. Strip off you last commit
2. Accept you fix
3. Create an issue to fix the audio, video confusion

**Comment by Borewit** [comment]
Resetting the branch to the previous commit did result in an immediate close of the branch after force pushing it. I did my best to fix it in #343.

**Comment by Borewit** [comment]
Fixed in [v5.0.2](https://github.com/Borewit/music-metadata/releases/tag/v5.0.2)

**Pull request closed without merging**
