### PR TITLE
Extending Ogg parser with Opus codec support.

### PR DESCRIPTION
**Pull request by Borewit**
Implements issue #47.

### CODE REVIEW

**Comment by Borewit** [comment]
@Extarys: you could already try the Opus parsing from the devlopment branch:
`npm install Borewit/music-metadata#feature/Opus`

If you are willing to review the changes, that would be great.

And cover art works as well in combination with Opus :wink:

**Comment by Extarys** [comment]
Awesome, will try in the next 24hrs ;)

**Comment by Extarys** [comment]
Tested 15 different files from different artists and it looks ok.
Example output:
{ format: 
   { dataformat: 'Ogg/Opus',
     sampleRate: 44100,
     numberOfChannels: 2,
     numberOfSamples: 10598400,
     duration: 240.3265306122449,
     tagTypes: [ 'vorbis' ] },
  native: undefined,
  common: 
   { track: { no: 1, of: 4 },
     disk: { no: 1, of: 1 },
     album: 'Living on My Own',
     albumartist: 'Freddie Mercury',
     artist: 'Freddie Mercury',
     composer: [ 'Freddie Mercury' ],
     year: 1993,
     date: '1993',
     genre: [ 'Dance' ],
     picture: [ [Object] ],
     title: 'Living on My Own (radio mix)',
     artists: [ 'Freddie Mercury' ] } }

Awesome job.

**Comment by Borewit** [comment]
@Extarys: Thx for the review Jeremy, lets release it.

**Comment by Extarys** [comment]
@Borewit is the best.

**Pull request merged**
