### PR TITLE
[WIP] feat: allow to populate common tags with information of all tag headers

### PR DESCRIPTION
**Pull request by AoDev**
### WIP
- [ ] tests: need to add unit tests (need some info)
- [ ] confirm the name of the option

### PR details

Adding a new parsing option to enable a "best effort" approach while
trying to get information from all available tag headers when possible.

If the same information is available in multiple headers, the priority
is given to the newest version of the header.

eg:
* [ID3v1.1] artist: "Some artist"
* [ID3v2.4] artist: "Another artist"

The result will be that artist is "Another artist" in common.

Relates to: https://github.com/Borewit/music-metadata/issues/72

### CODE REVIEW

**Comment by AoDev** [comment]
@Borewit I have started what we discussed in #72. 
Regarding unit tests, do you know some good tag editor that could let me update ID3v1 and ID3v2 independently?

**Comment by Borewit** [comment]
> Regarding unit tests, do you know some good tag editor that could let me update ID3v1 and ID3v2 independently?

No not directly, that is why I asked you the sample ;-)

Sometimes I end up with cutting the file in pieces, copying header part to a file and reconstruct the file parts. Using a tool like [MPEGAudioInfo](https://www.codeproject.com/Articles/8295/MPEG-Audio-Frame-Header) to figure out where ID3v2 headers are located. ID3v1 are the last 128 bytes, that's an easy one.

**Comment by AoDev** [comment]
@Borewit 

I have got a sample with some differences in ID3v1.1 and ID3v2.4 tag headers. :)
But, I am blocked regarding the artist in `common`.

Could you explain the reasoning [behind the artist code](https://github.com/Borewit/music-metadata/blob/master/src/index.ts#L394)?

In my test, I am checking that the ID3v2.4 artist should have the priority over the one in ID3v1.1.
But, I saw that it's possible to have multiple artists.

Especially there is a check where:

```javascript
if (metadata.common.artist.length > 1) {
  delete metadata.common.artist;
} else {
  metadata.common.artist = metadata.common.artist[0];
}
```

I am trying to understand what the test / expected should yield.
You can have a better idea with the output of the test:

```javascript
  MPEG parsing
    Multiple ID3 tags: ID3v2.3, ID3v2.4 & ID3v1.1
      mergeTagHeaders option

// ID3v2.4
[ { id: 'TPE1', value: 'Dethklok' },
  { id: 'TCON', value: 'Metal' },
  { id: 'TIT2', value: 'Deththeme' } ]

// ID3v1.1
[ { id: 'artist', value: 'Mispelled artist deathklok' },
  { id: 'album', value: 'The Dethalbum' },
  { id: 'genre', value: 'Metal' } ]

// Common
{ track: { no: null, of: null },
  disk: { no: null, of: null },
  album: 'The Dethalbum',
  genre: [ 'Metal', 'Metal' ],
  title: 'Deththeme',
  // no artist?
  artists: [ 'Mispelled artist deathklok', 'Dethklok' ] }
        1) should merge multiple headers information when true
        ✓ should NOT merge multiple headers information when undefined
        ✓ should NOT merge multiple headers information when false


  2 passing (46ms)
  1 failing

  1) MPEG parsing
       Multiple ID3 tags: ID3v2.3, ID3v2.4 & ID3v1.1
         mergeTagHeaders option
           should merge multiple headers information when true:
     AssertionError: expected undefined to equal 'Dethklok'
      at /Volumes/DataUser/git-repos/3rd/music-metadata-my-fork/test/test-mpeg.js:243:23
      at <anonymous>

```

**Comment by Borewit** [comment]
> Especially there is a check where:
> https://github.com/Borewit/music-metadata/blob/5492b2d8df743c6a621d910d3fe1c82251e712a4/src/index.ts#L399-L403

|  tag | definition |
| ------------- | ------------- |
| common.artist  | Track artist, e.g. _'Joe Bonamassa & Beth Hart_ |
| common.artist  | Track artists e.g. ['Joe Bonamassa', 'Beth Hart]  |

Note that it is not always clear how the native artist tags are filled. But if we found _Madonna_ as the only artist tag, it is probably safe to fill both _common.artist_  and _common.artists_.

I follow [the way MusicBrainz Picard writes metadata](https://picard.musicbrainz.org/docs/tags/) to audio files. [MusicBrainz](https://musicbrainz.org/) is about clearly identifying music media releases, which a step further having an artist and track title in a display of computer. This enables 'the computer' to have semantical understanding, this helps to buildup your music collection DB much better, and could help to find additional information in the web. At the same time I started form the musicmetada repo which had a very simplistic _common_ model, I tried to keep backward-compatibility at the same time.

Sorry if I only clarified half of your issue, I don't have a lot of time now.

**Comment by AoDev** [comment]
@Borewit Hi :) I am continuing with this proposal, I had to pause this for a while.
I saw you checked [kaiku](https://github.com/AoDev/kaiku-music-player) 😃  (I am refactoring it from musicmetadata to music-metadata in [a branch](https://github.com/AoDev/kaiku-music-player/pull/7/commits/3854e8e67249f7a14bccdd11ce99d3597f0cd04c))

I was wondering a few things regarding `artist` / `artists`.

Multiple artists in the `artist` tag are defined by separating the names with `/` or `0x00`.
This is reflected in the [frameparser](https://github.com/Borewit/music-metadata/blob/master/src/id3v2/FrameParser.ts#L199).

`artists` isn't an official tag, is it? I mean ID3v1/v2 only have `artist`. (TPE1) So when you refer to _how Picard writes metadata_, am I right saying Picard does not write any `artists` tag but just `artist`?

Explaining more what I am investigating about the artist tag:

* Why do we delete the `artist` field if it's an array?

There is a special case for [artist when assigning it to common](https://github.com/Borewit/music-metadata/blob/master/src/common/GenericTagMapper.ts#L170).
The code explicitly creates an array for "artist" but then it is removed.

shouldn't it be?

```js
if (metadata.common.artist.length > 1) {
  metadata.common.artist = metadata.common.artist.join(' & ');
  // delete metadata.common.artist;
} else {
  metadata.common.artist = metadata.common.artist[0];
}
```
Effectively doing what you described:

`artists: ['Joe Bonamassa', 'Beth Hart] -> artist: 'Joe Bonamassa & Beth Hart'`

* There is also this [comment about the internal use of string[]] (https://github.com/Borewit/music-metadata/blob/master/src/index.ts#L28) that seems to indicate something to be aware of. Maybe we could add some more details in a comment?

_Note: I understand this discussion is a bit complicated through Github comments, so, if you have time some day, we could do this in a chat, in Gitter or something._

**Comment by Borewit** [comment]
That's great you are that you are picking up the job, I was a bit  afraid you gave up.

Nothing in 'common' is official, convenient at most. If a tag called artist, can contain multiple values, one could say I can hold several artists right?

I noticed a made type in my previous comment:

|  tag | definition |
| ------------- | ------------- |
| common.artist  | Track artist, e.g. _'Joe Bonamassa & Beth Hart_ |
| common.artist**s**  | Track artists e.g. ['Joe Bonamassa', 'Beth Hart]  |

So the artist**s** aims to list each contributing artist individual. That is what MusicBrainz does. The artist however captures the artist credits as written, e.g.: 'Joe Bonamassa & Beth Hart'. Secondly, it provides backwards compatibility to the predecessor musicmetadata project.

Is a perfect, not it's not. With albumartist there is no clear distinction for example, and I have to look it up myself if folks like yourself are asking for it.

Maybe you figured out a better approach.

Sure, we can chat. Please check if you got my e-mail.

**Pull request merged**
