### PR TITLE
Fix bitrate (`format.bitrate`) for WAV files

### LINKED ISSUE #1480: Bitrate calculation for WAV files is wrong
**Issue**

The `bitrate` for any 2 channel, 16-bit, wave file will result in a bitrate of 352600, which is wrong. It should be 44100 * 16 * 2 = 1411200.

Looking at there is an issue:
https://github.com/Borewit/music-metadata/blob/773b406b6398546a76d36ab3038b6526b2977ac8/lib/wav/WaveParser.ts#L122

The calculation is wrong and should be similar to:
https://github.com/Borewit/music-metadata/blob/773b406b6398546a76d36ab3038b6526b2977ac8/lib/wav/WaveParser.ts#L91

### PR DESCRIPTION
**Pull request by avwie**
Resolves #1480

### CODE REVIEW

**Review by Borewit — CHANGES_REQUESTED** [review]
Can you please include a unit test, validating the bitrate which is a double checked value?
You can use an existing WAX sample or extend one of the existing tests.

The fact that this error went unnoticed for so long and that you have been able to change the calculation without that a single unit tests failed shows how important unit tests are.

**Comment by avwie** [comment]
Allrighty, I added unit tests. Had to modify the bitrate calculation for ADPCM. Luckily ADPCM is fixed to 352kpbs.

**Review by Borewit — APPROVED** [review]

**Comment by Borewit** [comment]
Part of [v7.13.2](https://github.com/Borewit/music-metadata/releases/tag/v7.13.2) & [v8.1.2](https://github.com/Borewit/music-metadata/releases/tag/v8.1.2)

**Comment by avwie** [comment]
Awesome fast response! Dankjewel!

**Comment by Borewit** [comment]
Jij ook bedankt Arjan!

**Pull request merged**
