### PR TITLE
Fix ID3v2.3 & ID3v2.4 `USLT` mapping to `common.lyrics`

### PR DESCRIPTION
**Pull request by Borewit**
Related to #1974, fixes id3v2.4 `USLT` mapping to `common.lyrics`

References:
- https://id3.org/id3v2.3.0#Unsychronised_lyrics.2Ftext_transcription
- https://id3.org/id3v2.4.0-frames

### CODE REVIEW

**Comment by ffxsam** [comment]
@Borewit Thanks a ton! Will keep an eye out for when this is published to npm.

**Comment by Borewit** [comment]
> @Borewit Thanks a ton! Will keep an eye out for when this is published to npm.

Sorry, busy, forgot about it

**Comment by Borewit** [comment]
Part of [v8.3.0](https://github.com/Borewit/music-metadata/releases/tag/v8.3.0)

**Comment by ffxsam** [comment]
@Borewit You rock! Thanks for fixing both lyrics & grouping! Sending an extra donation your way shortly. 🙏 

Quick question: I noticed `common.lyrics` is an array. Any reason this is the case? From what I can tell, even if there are multiple lines, it's just a single string separated by newlines. Unless there's some way to add multiple versions of lyrics or something?

**Pull request merged**
