### PR TITLE
prototype: allow user to specify which parsers to import

### PR DESCRIPTION
**Pull request by minht11**
This is very rough prototype of https://github.com/Borewit/music-metadata/issues/894 to see if there is a way forward.

This implements ability for users to import only parsers they need, thus making bundle size smaller.
```ts
import { parserBlob } from 'music-metadata/without-parsers';
import { MpegParser } from 'music-metadata/parsers';

parserBlob(blob, { parsers: [MpegParser] })
```
If user want to use all of the parsers (as with the current version) they can import them all at once.
```ts
import { parserBlob } from 'music-metadata/without-parsers';
import { ALL_PARSERS } from 'music-metadata/parsers';

parserBlob(blob, { parsers: ALL_PARSERS })
```

To support this code changes are quite minimal, however there are few open questions:

1. Should passing parsers be required? That would be breaking change requiring new major version, in this prototype separate entrypoints are added, to prevent existing users from breaking, but I am leaning towards that being overkill since fix is just to import `ALL_PARSERS`.
2. Should we hide parser implementations? This feature technically could allow for user supplied custom parsers or modifying existing ones. To prevent that we could make publicly exposed parsers be black box like this:
```ts
const implSymbol = Symbol('internal');

class MpegParser {
  static parseTypes = ['mpeg'];

  static [implSymbol] = MpegParserImpl;
} 
``` 

@Borewit what do do you think of the idea? If you would allow I would try to submit proper implementation.

### CODE REVIEW

**Comment by Borewit** [comment]
> Should passing parsers be required? That would be breaking change requiring new major version, in this prototype separate entrypoints are added, to prevent existing users from breaking, but I am leaning towards that being overkill since fix is just to import ALL_PARSERS.

If make this the default, there are no breaking changes, right? 
```js
parserBlob(blob, { parsers: ALL_PARSERS })
```

So if not parsers are provided, `options.parsers` will be initialized with `ALL_PARSERS`.

**Comment by minht11** [comment]
There will be no breaking changes for current entry point users because all parsers are provided:
```ts
if (!options.parsers) {
    options.parsers = ALL_PARSERS; // the same behavior as before, but not treeshakable.
  }
```
However those users will not benefit from treeshaking, to opt into that you would need to import from separate entry point `'music-metadata/without-parsers'`, but not a huge deal.

**Comment by Borewit** [comment]
What about [https://webpack.js.org/guides/lazy-loading/](https://webpack.js.org/guides/lazy-loading/) where you may want to start with the lightest parser required, but maybe load parsers as required.

**Comment by minht11** [comment]
User configurable parsers would still be nice, but are less needed now because of https://github.com/Borewit/music-metadata/pull/2231. Closing.

**Pull request closed without merging**
