### PR TITLE
Fix ID3v2 GEOB parsing

### PR DESCRIPTION
**Pull request by jirihybek**
The ID3v2 frame parser was not parsing correctly GEOB fields:
- It was basically cutting the description too soon if data were too short due to incorrect length expression.
- Description characters were leaking to the data array due to invalid offset computation.

Now fixed.

Related to: #406

### CODE REVIEW

**Comment by Borewit** [comment]
Great contribution, do you sample by an change, which demonstrates the bug you have addressed, @jirihybek ? We can strip of the audio part, to avoid copyright infringement.

**Comment by jirihybek** [comment]
The problem is with Serato DJ meta-data which are stored as GEOBs.

The sample audio file with Serato meta-data:
[high-end-hustle-fashion-luxury-disco-253184.mp3.txt](https://github.com/user-attachments/files/17692859/high-end-hustle-fashion-luxury-disco-253184.mp3.txt)

Attribution: Music by [Rockot](https://pixabay.com/users/rockot-1947599/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=253184) from [Pixabay](https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=253184).

It has .txt extension since GitHub doesn't allow to upload MP3 directly.

Here is the full reproduction code:
```javascript
import { parseFile } from 'music-metadata';

const filename = 'high-end-hustle-fashion-luxury-disco-253184.mp3.txt';

const metadata = await parseFile(filename);
const nativeTags = metadata.native["ID3v2.4"] ?? metadata.native["ID3v2.3"];
const geobObjects = nativeTags.filter((frame) => frame.id === "GEOB");

geobObjects.forEach((geobObject) => {
    const value = geobObject.value;
    console.log({
        type: value.type,
        filename: value.filename,
        description: value.description,
        data: new TextDecoder().decode(value.data)
    });
});
```

---

The output **before fix** (binary data are stripped out):

Notice the description "overflowing" to data incl. null-termination byte, or missing entirely.

```
{
  type: "application/octet-stream",
  filename: "",
  description: "Serato Overview",
  data: "erato Overview\u0000\u0001...",
}
{
  type: "application/octet-stream",
  filename: "",
  description: "",
  data: "erato Analysis\u0000\u0002...",
}
{
  type: "application/octet-stream",
  filename: "",
  description: "Serato Auto",
  data: "erato Autotags\u0000\u0001...",
}
{
  type: "application/octet-stream",
  filename: "",
  description: "Serato Markers_",
  data: "erato Markers_\u0000\u0002\u0005...",
}
{
  type: "application/octet-stream",
  filename: "",
  description: "Serato Markers2",
  data: "erato Markers2\u0000\u0001\u0001...",
}
{
  type: "application/octet-stream",
  filename: "",
  description: "Sera",
  data: "erato BeatGrid\u0000\u0001...",
}
```

The output after fix:

```
{
  type: "application/octet-stream",
  filename: "",
  description: "Serato Overview",
  data: "\u0001...",
}
{
  type: "application/octet-stream",
  filename: "",
  description: "Serato Analysis",
  data: "\u0002...",
}
{
  type: "application/octet-stream",
  filename: "",
  description: "Serato Autotags",
  data: "\u0001...",
}
{
  type: "application/octet-stream",
  filename: "",
  description: "Serato Markers_",
  data: "\u0002\u0005...",
}
{
  type: "application/octet-stream",
  filename: "",
  description: "Serato Markers2",
  data: "\u0001\u0001...",
}
{
  type: "application/octet-stream",
  filename: "",
  description: "Serato BeatGrid",
  data: "\u0001...",
}
```

**Comment by Borewit** [comment]
@jirihybek Interested to add support for decoding [Serato tags](https://github.com/Holzhaus/serato-tags/) ?

**Comment by Borewit** [comment]
Fixed in [v10.6.0](https://github.com/Borewit/music-metadata/releases/tag/v10.6.0)

**Pull request merged**
